[package]
name = "plc_timer"
version = "2024.9.30"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0" }

tracing = { version = "0.1.40" }


[build-dependencies]
plc_build = { path = "../plc_build" }
